[package]
name = "southstar-spellcheck"
description = "Optional spell checking of editable text over the Enchant library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
southstar-glib = { path = "../glib" }

[features]
enchant = []

[lints]
workspace = true
