//! Southstar — the JavaScript that builds a frame's window: the global bootstrap run in a frame realm, the scope wrapped around frame scripts run in the page realm, and the cross-origin window proxy.
//! Copyright 2026 Andreas Røsdal
//! SPDX-License-Identifier: LicenseRef-NSL-1.0 OR GPL-3.0-or-later

pub(crate) const SCOPE: &str = concat!(
    "(function(realWin, iframeDoc, initialURL, sandbox, docURL){",
    "  var url = initialURL || 'about:blank';",
    "  var shown = docURL || '';",
    "  function vis(){ return shown || url; }",
    "  var hashL = [], popL = [], onhash = null, onpop = null, state = null;",
    "  var msgL = [], onmsg = null;",
    "  var win;",
    "  function mk(u, b){ try { return new realWin.URL(u, b || url); } catch(e){ return null; } }",
    "  function fire(list, on, ev){",
    "    var c = list.slice();",
    "    for (var i=0;i<c.length;i++){ try { c[i].call(win, ev); } catch(e){} }",
    "    if (on) { try { on.call(win, ev); } catch(e){} }",
    "  }",
    "  function evt(type, props){",
    "    var e = null;",
    "    try { if (realWin.Event) { e = new realWin.Event(type); } } catch(x){}",
    "    if (!e) e = { type: type };",
    "    if (props) for (var k in props) { try { e[k] = props[k]; } catch(x){} }",
    "    return e;",
    "  }",
    "  function fireHash(o, n){ fire(hashL, onhash, evt('hashchange', {oldURL:o, newURL:n})); }",
    "  function firePop(){ fire(popL, onpop, evt('popstate', {state:state})); }",
    "  function sameDoc(a, b){ var ua=mk(a), ub=mk(b);",
    "    return !!ua && !!ub && ua.origin===ub.origin && ua.pathname===ub.pathname && ua.search===ub.search; }",
    "  var loc = {};",
    "  ['protocol','host','hostname','port','pathname','search','origin'].forEach(function(p){",
    "    Object.defineProperty(loc, p, { configurable:true, enumerable:true,",
    "      get: function(){ var u=mk(vis()); return u ? u[p] : ''; } }); });",
    "  Object.defineProperty(loc, 'href', { configurable:true, enumerable:true,",
    "    get: function(){ return vis(); },",
    "    set: function(v){ var u=mk(v);",
    "      if(!u) throw new DOMException('location: invalid URL','SyntaxError');",
    "      var o=vis(); url=u.href; shown='';",
    "      if (o!==url && sameDoc(o,url)) fireHash(o,url); } });",
    "  Object.defineProperty(loc, 'hash', { configurable:true, enumerable:true,",
    "    get: function(){ var u=mk(vis()); return u ? u.hash : ''; },",
    "    set: function(v){ var u=mk(vis()); if(!u) return; u.hash=v; var o=vis();",
    "      if (shown) shown=u.href; else url=u.href;",
    "      if (o!==vis()) fireHash(o,vis()); } });",
    "  loc.assign = function(v){ this.href = v; };",
    "  loc.replace = function(v){ this.href = v; };",
    "  loc.reload = function(){};",
    "  loc.toString = function(){ return vis(); };",
    "  var topHist = realWin.history;",
    "  var topPush = topHist && topHist.pushState, topReplace = topHist && topHist.replaceState;",
    "  var hist = {",
    "    get state(){ return state; }, get length(){ return 1; }, scrollRestoration:'auto',",
    "    pushState: function(s,t,u){ if (this === topHist && topPush) return topPush.apply(topHist, arguments);",
    "      state=s; if(u!=null){ var n=mk(u); if(n){ url=n.href; shown=''; } } },",
    "    replaceState: function(s,t,u){ if (this === topHist && topReplace) return topReplace.apply(topHist, arguments);",
    "      state=s; if(u!=null){ var n=mk(u); if(n){ url=n.href; shown=''; } } },",
    "    back: function(){ firePop(); }, forward: function(){ firePop(); }, go: function(){ firePop(); }",
    "  };",
    "  var ov = {",
    "    location: loc, history: hist, document: iframeDoc,",
    "    fetch: function(input, init){",
    "      var req = input;",
    "      try { if (typeof input === 'string') { var u = mk(input); if (u) req = u.href; } } catch(e){}",
    "      return realWin.fetch.call(win, req, init); },",
    "    get onhashchange(){ return onhash; }, set onhashchange(v){ onhash=v; },",
    "    get onpopstate(){ return onpop; }, set onpopstate(v){ onpop=v; },",
    "    get onmessage(){ return onmsg; }, set onmessage(v){ onmsg=v; },",
    "    __nsDeliverMessage: function(ev){ fire(msgL, onmsg, ev); },",
    "    postMessage: realWin.__nsPostMessageThis,",
    "    addEventListener: function(type, fn, o){",
    "      if (type==='hashchange'){ hashL.push(fn); return; }",
    "      if (type==='popstate'){ popL.push(fn); return; }",
    "      if (type==='message'){ msgL.push(fn); return; }",
    "      return realWin.addEventListener(type, fn, o); },",
    "    removeEventListener: function(type, fn, o){",
    "      var i; if (type==='hashchange'){ i=hashL.indexOf(fn); if(i>=0) hashL.splice(i,1); return; }",
    "      if (type==='popstate'){ i=popL.indexOf(fn); if(i>=0) popL.splice(i,1); return; }",
    "      if (type==='message'){ i=msgL.indexOf(fn); if(i>=0) msgL.splice(i,1); return; }",
    "      return realWin.removeEventListener(type, fn, o); },",
    "    dispatchEvent: function(ev){",
    "      if (ev && ev.type==='hashchange'){ fire(hashL, onhash, ev); return true; }",
    "      if (ev && ev.type==='popstate'){ fire(popL, onpop, ev); return true; }",
    "      if (ev && ev.type==='message'){ fire(msgL, onmsg, ev); return true; }",
    "      return realWin.dispatchEvent(ev); }",
    "  };",
    "  if (sandbox & 1) {",
    "    if (!(sandbox & 32)) {",
    "      ov.alert = function(){};",
    "      ov.confirm = function(){ return false; };",
    "      ov.prompt = function(){ return null; };",
    "      ov.print = function(){};",
    "    }",
    "    if (!(sandbox & 16)) { ov.open = function(){ return null; }; }",
    "  }",
    "  if ((sandbox & 8192) || ((sandbox & 1) && !(sandbox & 8))) {",
    "    var denyStore = function(){",
    "      try { return new realWin.DOMException('The operation is insecure.', 'SecurityError'); }",
    "      catch(e){ return new Error('SecurityError'); } };",
    "    Object.defineProperty(ov, 'localStorage', { configurable:true, get: function(){ throw denyStore(); } });",
    "    Object.defineProperty(ov, 'sessionStorage', { configurable:true, get: function(){ throw denyStore(); } });",
    "    Object.defineProperty(ov, 'indexedDB', { configurable:true, get: function(){ throw denyStore(); } });",
    "  }",
    "  function ovGet(p){",
    "    var d = Object.getOwnPropertyDescriptor(ov, p);",
    "    return d && d.get ? d.get.call(ov) : ov[p];",
    "  }",
    "  function ovSet(p, v){",
    "    var d = Object.getOwnPropertyDescriptor(ov, p);",
    "    if (d && d.set){ d.set.call(ov, v); return true; }",
    "    if (d && d.writable===false) return false;",
    "    ov[p] = v; return true;",
    "  }",
    "  win = new Proxy(realWin, {",
    "    get: function(t, p){",
    "      if (p==='window'||p==='self'||p==='globalThis'||p==='frames') return win;",
    "      if (p==='parent') return realWin;",
    "      if (p==='top') return realWin.top && typeof realWin.top === 'object' ? realWin.top : realWin;",
    "      if (Object.prototype.hasOwnProperty.call(ov, p)) return ovGet(p);",
    "      return Reflect.get(t, p, t); },",
    "    set: function(t, p, v){",
    "      if (p==='location'){ loc.href = v; return true; }",
    "      return ovSet(p, v); },",
    "    defineProperty: function(t, p, d){ try { Object.defineProperty(ov, p, d); return true; } catch(e){ return false; } },",
    "    getOwnPropertyDescriptor: function(t, p){",
    "      if (Object.prototype.hasOwnProperty.call(ov, p)) return Object.getOwnPropertyDescriptor(ov, p);",
    "      return Reflect.getOwnPropertyDescriptor(t, p); },",
    "    deleteProperty: function(t, p){ if (Object.prototype.hasOwnProperty.call(ov, p)) return delete ov[p]; return true; },",
    "    ownKeys: function(t){",
    "      var seen = Object.create(null), out = [];",
    "      Reflect.ownKeys(t).forEach(function(k){ seen[k]=1; out.push(k); });",
    "      Reflect.ownKeys(ov).forEach(function(k){ if(!seen[k]) out.push(k); });",
    "      return out; },",
    "    has: function(t, p){ return Object.prototype.hasOwnProperty.call(ov, p) || (p in t); }",
    "  });",
    "  return { window: win, location: loc, history: hist };",
    "})",
);

pub(crate) const GLOBAL: &str = concat!(
    "(function(G, realWin, iframeDoc, initialURL, sandbox, platformNames, frameEl, frameName, childFrameOf, framePostMessage, docURL, realmClone, windowEvents){",
    "  var url = initialURL || 'about:blank';",
    "  var shown = docURL || '';",
    "  function vis(){ return shown || url; }",
    "  var hashL = [], popL = [], onhash = null, onpop = null, state = null;",
    "  var msgL = [], onmsg = null;",
    "  var win = G;",
    "  function mk(u, b){ try { return new realWin.URL(u, b || url); } catch(e){ return null; } }",
    "  function fire(list, on, ev){",
    "    var c = list.slice();",
    "    for (var i=0;i<c.length;i++){ try { c[i].call(win, ev); } catch(e){} }",
    "    if (on) { try { on.call(win, ev); } catch(e){} }",
    "  }",
    "  function evt(type, props){",
    "    var e = null;",
    "    try { if (realWin.Event) { e = new realWin.Event(type); } } catch(x){}",
    "    if (!e) e = { type: type };",
    "    if (props) for (var k in props) { try { e[k] = props[k]; } catch(x){} }",
    "    return e;",
    "  }",
    "  function fireHash(o, n){ fire(hashL, onhash, evt('hashchange', {oldURL:o, newURL:n})); }",
    "  function firePop(){ fire(popL, onpop, evt('popstate', {state:state})); }",
    "  function sameDoc(a, b){ var ua=mk(a), ub=mk(b);",
    "    return !!ua && !!ub && ua.origin===ub.origin && ua.pathname===ub.pathname && ua.search===ub.search; }",
    "  var loc = {};",
    "  ['protocol','host','hostname','port','pathname','search','origin'].forEach(function(p){",
    "    Object.defineProperty(loc, p, { configurable:true, enumerable:true,",
    "      get: function(){ var u=mk(vis()); return u ? u[p] : ''; } }); });",
    "  Object.defineProperty(loc, 'href', { configurable:true, enumerable:true,",
    "    get: function(){ return vis(); },",
    "    set: function(v){ var u=mk(v);",
    "      if(!u) throw new DOMException('location: invalid URL','SyntaxError');",
    "      var o=vis(); url=u.href; shown='';",
    "      if (o!==url && sameDoc(o,url)) fireHash(o,url); } });",
    "  Object.defineProperty(loc, 'hash', { configurable:true, enumerable:true,",
    "    get: function(){ var u=mk(vis()); return u ? u.hash : ''; },",
    "    set: function(v){ var u=mk(vis()); if(!u) return; u.hash=v; var o=vis();",
    "      if (shown) shown=u.href; else url=u.href;",
    "      if (o!==vis()) fireHash(o,vis()); } });",
    "  loc.assign = function(v){ this.href = v; };",
    "  loc.replace = function(v){ this.href = v; };",
    "  loc.reload = function(){};",
    "  loc.toString = function(){ return vis(); };",
    "  var topHist = realWin.history;",
    "  var topPush = topHist && topHist.pushState, topReplace = topHist && topHist.replaceState;",
    "  var hist = {",
    "    get state(){ return state; }, get length(){ return 1; }, scrollRestoration:'auto',",
    "    pushState: function(s,t,u){ if (this === topHist && topPush) return topPush.apply(topHist, arguments);",
    "      state=s; if(u!=null){ var n=mk(u); if(n){ url=n.href; shown=''; } } },",
    "    replaceState: function(s,t,u){ if (this === topHist && topReplace) return topReplace.apply(topHist, arguments);",
    "      state=s; if(u!=null){ var n=mk(u); if(n){ url=n.href; shown=''; } } },",
    "    back: function(){ firePop(); }, forward: function(){ firePop(); }, go: function(){ firePop(); }",
    "  };",
    "  function def(name, d){ d.configurable = true; try { Object.defineProperty(G, name, d); } catch(e){} }",
    "  def('window',     { value: win, writable: true });",
    "  def('self',       { value: win, writable: true });",
    "  def('event',      { value: undefined, writable: true });",
    "  var crossWindows = new WeakMap();",
    "  function crossWindow(target, up){",
    "    if (crossWindows.has(target)) return crossWindows.get(target);",
    "    var proxy, loc = {};",
    "    function denied(){ throw new DOMException('Blocked cross-origin frame access', 'SecurityError'); }",
    "    function childFrame(p){",
    "      if (typeof p !== 'string' || typeof childFrameOf !== 'function') return undefined;",
    "      var child;",
    "      try { child = childFrameOf(target, p); } catch (e) { return undefined; }",
    "      return child && typeof child === 'object' ? crossWindow(child, proxy) : undefined; }",
    "    Object.defineProperty(loc, 'href', { enumerable:true, set:function(v){ target.location.href=v; }, get:denied });",
    "    loc.replace = function(v){ target.location.replace(v); };",
    "    proxy = new Proxy({}, {",
    "      get:function(t,p){",
    "        if(p==='window'||p==='self'||p==='frames') return proxy;",
    "        if(p==='parent') return up || proxy;",
    "        if(p==='top') return up ? up.top : proxy;",
    "        if(p==='postMessage') return function(){ return realWin.__nsPostMessageFrom.apply(realWin, [target, G].concat(Array.prototype.slice.call(arguments))); };",
    "        if(p==='location') return loc;",
    "        if(p==='closed') return !!target.closed;",
    "        if(p==='length') return target.length >>> 0;",
    "        if(p==='close'||p==='focus'||p==='blur') return function(){ return target[p](); };",
    "        if(p===Symbol.toStringTag) return 'Window';",
    "        var child = childFrame(p); if(child) return child;",
    "        return denied(); },",
    "      set:function(t,p,v){ if(p==='location'){ target.location.href=v; return true; } return denied(); },",
    "      has:function(t,p){ return p==='window'||p==='self'||p==='frames'||p==='parent'||p==='top'||",
    "        p==='postMessage'||p==='location'||p==='closed'||p==='length'||p==='close'||p==='focus'||p==='blur'||",
    "        !!childFrame(p); }",
    "    });",
    "    crossWindows.set(target, proxy);",
    "    return proxy;",
    "  }",
    "  var parentWin = (sandbox & 8192) ? crossWindow(realWin) : realWin;",
    "  var topWin = (sandbox & 8192) ? parentWin :",
    "    (realWin.top && typeof realWin.top === 'object' ? realWin.top : realWin);",
    "  def('__ndParentWindowProxy', { value: parentWin });",
    "  def('top',        { value: topWin, writable: true });",
    "  def('parent',     { value: parentWin, writable: true });",
    "  def('frames',     { value: win, writable: true });",
    "  def('document',   { value: iframeDoc, writable: true, enumerable: true });",
    "  def('history',    { value: hist, writable: true, enumerable: true });",
    "  def('location',   { enumerable: true, get: function(){ return loc; },",
    "                      set: function(v){ loc.href = v; } });",
    "  def('fetch', { writable: true, value: function(input, init){",
    "      var req = input;",
    "      try { if (typeof input === 'string') { var u = mk(input); if (u) req = u.href; } } catch(e){}",
    "      return realWin.fetch.call(win, req, init); } });",
    "  def('onhashchange', { get: function(){ return onhash; }, set: function(v){ onhash=v; } });",
    "  def('onpopstate',   { get: function(){ return onpop; }, set: function(v){ onpop=v; } });",
    "  def('onmessage',    { get: function(){ return onmsg; }, set: function(v){ onmsg=v; } });",
    "  function guardSource(ev){",
    "    var src; try { src = ev.source; } catch (e) { return; }",
    "    if (!src || typeof src !== 'object' || src === G || src === win) return;",
    "    var srcOrigin;",
    "    try { src.document; srcOrigin = src.location.origin; } catch (e) { return; }",
    "    if (srcOrigin === G.origin && G.origin !== 'null') return;",
    "    try { Object.defineProperty(ev, 'source', { value: crossWindow(src), configurable: true }); } catch (e) {}",
    "  }",
    "  def('__nsDeliverMessage', { value: function(ev){ guardSource(ev); fire(msgL, onmsg, ev); } });",
    "  def('postMessage',  { writable: true, value: framePostMessage });",
    "  def('addEventListener', { writable: true, value: function(type, fn, o){",
    "      if (type==='hashchange'){ hashL.push(fn); return; }",
    "      if (type==='popstate'){ popL.push(fn); return; }",
    "      if (type==='message'){ msgL.push(fn); return; }",
    "      return windowEvents.add.call(win, type, fn, o); } });",
    "  def('removeEventListener', { writable: true, value: function(type, fn, o){",
    "      var i; if (type==='hashchange'){ i=hashL.indexOf(fn); if(i>=0) hashL.splice(i,1); return; }",
    "      if (type==='popstate'){ i=popL.indexOf(fn); if(i>=0) popL.splice(i,1); return; }",
    "      if (type==='message'){ i=msgL.indexOf(fn); if(i>=0) msgL.splice(i,1); return; }",
    "      return windowEvents.remove.call(win, type, fn, o); } });",
    "  def('dispatchEvent', { writable: true, value: function(ev){",
    "      if (ev && ev.type==='hashchange'){ fire(hashL, onhash, ev); return true; }",
    "      if (ev && ev.type==='popstate'){ fire(popL, onpop, ev); return true; }",
    "      if (ev && ev.type==='message'){ fire(msgL, onmsg, ev); return true; }",
    "      return windowEvents.dispatch.call(win, ev); } });",
    "  if (sandbox & 1) {",
    "    if (!(sandbox & 32)) {",
    "      def('alert',   { writable: true, value: function(){} });",
    "      def('confirm', { writable: true, value: function(){ return false; } });",
    "      def('prompt',  { writable: true, value: function(){ return null; } });",
    "      def('print',   { writable: true, value: function(){} });",
    "    }",
    "    if (!(sandbox & 16)) { def('open', { writable: true, value: function(){ return null; } }); }",
    "  }",
    "  if ((sandbox & 8192) || ((sandbox & 1) && !(sandbox & 8))) {",
    "    var denyStore = function(){",
    "      try { return new realWin.DOMException('The operation is insecure.', 'SecurityError'); }",
    "      catch(e){ return new Error('SecurityError'); } };",
    "    def('localStorage',   { get: function(){ throw denyStore(); } });",
    "    def('sessionStorage', { get: function(){ throw denyStore(); } });",
    "    def('indexedDB',      { get: function(){ throw denyStore(); } });",
    "  }",
    "  if ((sandbox & 1) && !(sandbox & 16384) && iframeDoc) {",
    "    try { Object.defineProperty(iframeDoc, 'requestStorageAccess', {",
    "      configurable: true, writable: true, enumerable: true,",
    "      value: function requestStorageAccess(){ return Promise.reject(",
    "        new realWin.DOMException('Storage access is not allowed in this sandboxed document.', 'NotAllowedError')); } });",
    "    } catch (e) {}",
    "  }",
    "  var crossOrigin = (sandbox & 8192) !== 0;",
    "  var parentOnly = { cookieStore:1, caches:1, getSelection:1, opener:1, frameElement:1, origin:1, name:1, navigation:1, external:1 };",
    "  def('origin', { get: function(){ if ((sandbox & 1) && !(sandbox & 8)) return 'null'; var u=mk(url); return u ? u.origin : 'null'; } });",
    "  def('name', { value: frameName, writable: true });",
    "  function tagAs(obj, iface){",
    "    try { var proto = realWin[iface] && realWin[iface].prototype;",
    "      if (proto) Object.setPrototypeOf(obj, proto); } catch (e) {}",
    "    try { Object.defineProperty(obj, Symbol.toStringTag,",
    "      { value: iface, writable: false, enumerable: false, configurable: true }); } catch (e) {}",
    "  }",
    "  try { Object.defineProperty(G, Symbol.toStringTag,",
    "    { value: 'Window', writable: false, enumerable: false, configurable: true }); } catch (e) {}",
    "  tagAs(loc, 'Location');",
    "  tagAs(hist, 'History');",
    "  try {",
    "    ['timeline', 'pictureInPictureEnabled'].forEach(function(k){",
    "      if (iframeDoc && !(k in iframeDoc) && realWin.document && k in realWin.document)",
    "        Object.defineProperty(iframeDoc, k, { configurable: true, enumerable: true,",
    "          value: realWin.document[k] });",
    "    });",
    "  } catch (e) {}",
    "  def('frameElement', { value: crossOrigin ? null : (frameEl || null), writable: true });",
    "  function frameSize(prop, fallback){",
    "    return { configurable: true, enumerable: true,",
    "      get: function(){",
    "        try { var v = frameEl && frameEl[prop]; if (typeof v === 'number' && v >= 0) return v; } catch (e) {}",
    "        return realWin[fallback]; },",
    "      set: function(v){ Object.defineProperty(G, fallback, { value: v, writable: true, configurable: true, enumerable: true }); } };",
    "  }",
    "  try { Object.defineProperty(G, 'innerWidth', frameSize('clientWidth', 'innerWidth')); } catch (e) {}",
    "  try { Object.defineProperty(G, 'innerHeight', frameSize('clientHeight', 'innerHeight')); } catch (e) {}",
    "  if (crossOrigin) {",
    "    def('opener', { value: null, writable: true });",
    "    def('getSelection', { writable: true, value: function(){ return iframeDoc.getSelection ? iframeDoc.getSelection() : null; } });",
    "  }",
    "  try {",
    "    var pnames = Object.getOwnPropertyNames(realWin);",
    "    for (var pi = 0; pi < pnames.length; pi++) {",
    "      var pk = pnames[pi];",
    "      if (Object.prototype.hasOwnProperty.call(G, pk)) continue;",
    "      if (platformNames ? !Object.prototype.hasOwnProperty.call(platformNames, pk)",
    "                        : crossOrigin) continue;",
    "      if (crossOrigin && parentOnly[pk]) continue;",
    "      if (pk.charCodeAt(0) === 0xfffd) continue;",
    "      try {",
    "        var pd = Object.getOwnPropertyDescriptor(realWin, pk);",
    "        if (pd && platformNames && Object.prototype.hasOwnProperty.call(platformNames, pk)) {",
    "          if ('value' in pd) pd.value = realmClone(pd.value);",
    "          if (pd.get) pd.get = realmClone(pd.get);",
    "          if (pd.set) pd.set = realmClone(pd.set);",
    "        }",
    "        if (pd) Object.defineProperty(G, pk, pd);",
    "      } catch (e) {}",
    "    }",
    "  } catch (e) {}",
    "  if (typeof realWin.Range === 'function') {",
    "    var OrigRange = typeof G.Range === 'function' ? G.Range : realWin.Range;",
    "    var FrameRange = function Range(){",
    "      var r = Reflect.construct(OrigRange, arguments, new.target || FrameRange);",
    "      try { r.setStart(iframeDoc, 0); r.setEnd(iframeDoc, 0); } catch (e) {}",
    "      return r;",
    "    };",
    "    FrameRange.prototype = OrigRange.prototype;",
    "    try { Object.setPrototypeOf(FrameRange, OrigRange); } catch (e) {}",
    "    def('Range', { value: FrameRange, writable: true });",
    "  }",
    "  try { Object.setPrototypeOf(G, realmClone(Object.getPrototypeOf(realWin))); } catch (e) {}",
    "  return { location: loc, history: hist };",
    "})",
);

pub(crate) const CROSS_WINDOW: &str = concat!(
    "(function(G, target){",
    "  var cache = G.__ndCrossWindows;",
    "  if (!(cache instanceof WeakMap)) {",
    "    cache = new WeakMap();",
    "    Object.defineProperty(G, '__ndCrossWindows', { value: cache, configurable: true });",
    "  }",
    "  if (cache.has(target)) return cache.get(target);",
    "  var proxy, loc = {};",
    "  function denied(){ throw new DOMException('Blocked cross-origin frame access', 'SecurityError'); }",
    "  Object.defineProperty(loc, 'href', { enumerable:true, set:function(v){ target.location.href=v; }, get:denied });",
    "  loc.replace = function(v){ target.location.replace(v); };",
    "  loc.assign = function(v){ target.location.href=v; };",
    "  var allowed = ['window','self','frames','parent','top','opener','postMessage',",
    "    'location','closed','length','close','focus','blur'];",
    "  proxy = new Proxy({}, {",
    "    get:function(t,p){",
    "      if(p==='window'||p==='self'||p==='frames') return proxy;",
    "      if(p==='parent') return G.window || G;",
    "      if(p==='top') return G.top || G;",
    "      if(p==='opener') return null;",
    "      if(p==='postMessage') return function(){ return G.__nsPostMessageFrom.apply(G, [target, G].concat(Array.prototype.slice.call(arguments))); };",
    "      if(p==='location') return loc;",
    "      if(p==='closed') return !!target.closed;",
    "      if(p==='length') return target.length >>> 0;",
    "      if(p==='close'||p==='focus'||p==='blur') return function(){ return target[p](); };",
    "      if(p===Symbol.toStringTag) return 'Window';",
    "      return denied(); },",
    "    set:function(t,p,v){ if(p==='location'){ target.location.href=v; return true; } return denied(); },",
    "    has:function(t,p){ return allowed.indexOf(p) >= 0; },",
    "    ownKeys:function(){ return allowed.slice(); },",
    "    getOwnPropertyDescriptor:function(t,p){",
    "      if(allowed.indexOf(p) < 0) return undefined;",
    "      return { value: proxy[p], writable: false, enumerable: true, configurable: true }; },",
    "    defineProperty:function(){ return denied(); },",
    "    deleteProperty:function(){ return denied(); },",
    "    getPrototypeOf:function(){ return null; },",
    "    setPrototypeOf:function(){ return denied(); }",
    "  });",
    "  cache.set(target, proxy);",
    "  return proxy;",
    "})",
);
