//! Southstar — the CSS properties css.h enumerates, named so Rust can match on them and resolve their ids from css.c's property table.
//! Copyright 2026 Andreas Røsdal
//! SPDX-License-Identifier: LicenseRef-NSL-1.0 OR GPL-3.0-or-later

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Prop {
    Display,
    Color,
    BackgroundColor,
    FontSize,
    FontWeight,
    FontStyle,
    FontStretch,
    FontKerning,
    FontVariantLigatures,
    FontFeatureSettings,
    FontVariationSettings,
    FontFamily,
    TextAlign,
    MarginTop,
    MarginRight,
    MarginBottom,
    MarginLeft,
    PaddingTop,
    PaddingRight,
    PaddingBottom,
    PaddingLeft,
    BorderTopWidth,
    BorderRightWidth,
    BorderBottomWidth,
    BorderLeftWidth,
    BorderTopColor,
    BorderRightColor,
    BorderBottomColor,
    BorderLeftColor,
    BorderTopStyle,
    BorderRightStyle,
    BorderBottomStyle,
    BorderLeftStyle,
    Width,
    Height,
    MaxWidth,
    MaxHeight,
    MinWidth,
    MinHeight,
    LineHeight,
    TextDecoration,
    Position,
    Top,
    Right,
    Bottom,
    Left,
    ZIndex,
    Opacity,
    Cursor,
    PointerEvents,
    LetterSpacing,
    WordSpacing,
    WhiteSpace,
    BoxSizing,
    TextIndent,
    TextTransform,
    ListStyleType,
    VerticalAlign,
    Visibility,
    Overflow,
    FontVariant,
    BorderRadius,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderBottomRightRadius,
    BorderBottomLeftRadius,
    FlexDirection,
    FlexWrap,
    JustifyContent,
    AlignItems,
    AlignSelf,
    Gap,
    RowGap,
    ColumnGap,
    FlexGrow,
    FlexShrink,
    FlexBasis,
    Order,
    Float,
    Clear,
    BoxShadow,
    OutlineWidth,
    OutlineStyle,
    OutlineColor,
    OutlineOffset,
    BackgroundImage,
    BackgroundRepeat,
    BackgroundPositionX,
    BackgroundPositionY,
    BackgroundSize,
    BackgroundClip,
    BackgroundOrigin,
    BackgroundAttachment,
    ScrollbarWidth,
    ScrollbarColor,
    ImageRendering,
    Content,
    GridTemplateColumns,
    GridTemplateRows,
    GridTemplateAreas,
    GridColumn,
    GridRow,
    GridColumnStart,
    GridColumnEnd,
    GridRowStart,
    GridRowEnd,
    GridArea,
    GridAutoRows,
    GridAutoColumns,
    GridAutoFlow,
    Transform,
    TransformOrigin,
    Transition,
    Animation,
    AspectRatio,
    TextShadow,
    OverflowWrap,
    WordBreak,
    Hyphens,
    TextOverflow,
    TextDecorationColor,
    TextDecorationStyle,
    ListStylePosition,
    ListStyleImage,
    UserSelect,
    Quotes,
    ColumnCount,
    ColumnWidth,
    ColumnRuleWidth,
    ColumnRuleStyle,
    ColumnRuleColor,
    Filter,
    ClipPath,
    MixBlendMode,
    AccentColor,
    CounterReset,
    CounterIncrement,
    LineClamp,
    ObjectFit,
    ObjectPositionX,
    ObjectPositionY,
    MaskImage,
    OverflowX,
    OverflowY,
    Appearance,
    TableLayout,
    CaptionSide,
    BorderCollapse,
    BorderSpacing,
    ContainerType,
    ContainerName,
    CaretColor,
    TabSize,
    JustifyItems,
    JustifySelf,
    AlignContent,
    Direction,
    UnicodeBidi,
    Translate,
    Rotate,
    Scale,
    Perspective,
    PerspectiveOrigin,
    TransformBox,
    TransformStyle,
    BackfaceVisibility,
    AnimationPlayState,
    Clip,
    ContentVisibility,
    WritingMode,
    TextOrientation,
    TransitionDelay,
    TransitionDuration,
    AnimationDelay,
    AnimationDuration,
    Orphans,
    Widows,
    MaxLines,
    HyphenateLimitLines,
    ColumnSpan,
    BreakBefore,
    BreakAfter,
    BreakInside,
    ScrollSnapType,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollPaddingTop,
    ScrollPaddingRight,
    ScrollPaddingBottom,
    ScrollPaddingLeft,
    ScrollMarginTop,
    ScrollMarginRight,
    ScrollMarginBottom,
    ScrollMarginLeft,
    BorderImageSource,
    BorderImageSlice,
    BorderImageWidth,
    BorderImageOutset,
    BorderImageRepeat,
    Fill,
    FillOpacity,
    FillRule,
    Stroke,
    StrokeWidth,
    StrokeOpacity,
    StrokeLinecap,
    StrokeLinejoin,
    StrokeMiterlimit,
    StrokeDasharray,
    StrokeDashoffset,
    StopColor,
    StopOpacity,
    ClipRule,
    TextAnchor,
    DominantBaseline,
    PaintOrder,
    VectorEffect,
    ShapeRendering,
    SvgX,
    SvgY,
    Cx,
    Cy,
    R,
    Rx,
    Ry,
    AnimationName,
    AnimationTimingFunction,
    AnimationIterationCount,
    AnimationDirection,
    AnimationFillMode,
    TransitionProperty,
    TransitionTimingFunction,
    TransitionBehavior,
    AnimationTimeline,
    AnimationRangeStart,
    AnimationRangeEnd,
    AnimationComposition,
    CounterSet,
    OverflowClipMargin,
    WebkitBoxOrient,
    MaskClip,
    MaskComposite,
}

impl Prop {
    pub(crate) const ALL: [Prop; 242] = [
        Prop::Display,
        Prop::Color,
        Prop::BackgroundColor,
        Prop::FontSize,
        Prop::FontWeight,
        Prop::FontStyle,
        Prop::FontStretch,
        Prop::FontKerning,
        Prop::FontVariantLigatures,
        Prop::FontFeatureSettings,
        Prop::FontVariationSettings,
        Prop::FontFamily,
        Prop::TextAlign,
        Prop::MarginTop,
        Prop::MarginRight,
        Prop::MarginBottom,
        Prop::MarginLeft,
        Prop::PaddingTop,
        Prop::PaddingRight,
        Prop::PaddingBottom,
        Prop::PaddingLeft,
        Prop::BorderTopWidth,
        Prop::BorderRightWidth,
        Prop::BorderBottomWidth,
        Prop::BorderLeftWidth,
        Prop::BorderTopColor,
        Prop::BorderRightColor,
        Prop::BorderBottomColor,
        Prop::BorderLeftColor,
        Prop::BorderTopStyle,
        Prop::BorderRightStyle,
        Prop::BorderBottomStyle,
        Prop::BorderLeftStyle,
        Prop::Width,
        Prop::Height,
        Prop::MaxWidth,
        Prop::MaxHeight,
        Prop::MinWidth,
        Prop::MinHeight,
        Prop::LineHeight,
        Prop::TextDecoration,
        Prop::Position,
        Prop::Top,
        Prop::Right,
        Prop::Bottom,
        Prop::Left,
        Prop::ZIndex,
        Prop::Opacity,
        Prop::Cursor,
        Prop::PointerEvents,
        Prop::LetterSpacing,
        Prop::WordSpacing,
        Prop::WhiteSpace,
        Prop::BoxSizing,
        Prop::TextIndent,
        Prop::TextTransform,
        Prop::ListStyleType,
        Prop::VerticalAlign,
        Prop::Visibility,
        Prop::Overflow,
        Prop::FontVariant,
        Prop::BorderRadius,
        Prop::BorderTopLeftRadius,
        Prop::BorderTopRightRadius,
        Prop::BorderBottomRightRadius,
        Prop::BorderBottomLeftRadius,
        Prop::FlexDirection,
        Prop::FlexWrap,
        Prop::JustifyContent,
        Prop::AlignItems,
        Prop::AlignSelf,
        Prop::Gap,
        Prop::RowGap,
        Prop::ColumnGap,
        Prop::FlexGrow,
        Prop::FlexShrink,
        Prop::FlexBasis,
        Prop::Order,
        Prop::Float,
        Prop::Clear,
        Prop::BoxShadow,
        Prop::OutlineWidth,
        Prop::OutlineStyle,
        Prop::OutlineColor,
        Prop::OutlineOffset,
        Prop::BackgroundImage,
        Prop::BackgroundRepeat,
        Prop::BackgroundPositionX,
        Prop::BackgroundPositionY,
        Prop::BackgroundSize,
        Prop::BackgroundClip,
        Prop::BackgroundOrigin,
        Prop::BackgroundAttachment,
        Prop::ScrollbarWidth,
        Prop::ScrollbarColor,
        Prop::ImageRendering,
        Prop::Content,
        Prop::GridTemplateColumns,
        Prop::GridTemplateRows,
        Prop::GridTemplateAreas,
        Prop::GridColumn,
        Prop::GridRow,
        Prop::GridColumnStart,
        Prop::GridColumnEnd,
        Prop::GridRowStart,
        Prop::GridRowEnd,
        Prop::GridArea,
        Prop::GridAutoRows,
        Prop::GridAutoColumns,
        Prop::GridAutoFlow,
        Prop::Transform,
        Prop::TransformOrigin,
        Prop::Transition,
        Prop::Animation,
        Prop::AspectRatio,
        Prop::TextShadow,
        Prop::OverflowWrap,
        Prop::WordBreak,
        Prop::Hyphens,
        Prop::TextOverflow,
        Prop::TextDecorationColor,
        Prop::TextDecorationStyle,
        Prop::ListStylePosition,
        Prop::ListStyleImage,
        Prop::UserSelect,
        Prop::Quotes,
        Prop::ColumnCount,
        Prop::ColumnWidth,
        Prop::ColumnRuleWidth,
        Prop::ColumnRuleStyle,
        Prop::ColumnRuleColor,
        Prop::Filter,
        Prop::ClipPath,
        Prop::MixBlendMode,
        Prop::AccentColor,
        Prop::CounterReset,
        Prop::CounterIncrement,
        Prop::LineClamp,
        Prop::ObjectFit,
        Prop::ObjectPositionX,
        Prop::ObjectPositionY,
        Prop::MaskImage,
        Prop::OverflowX,
        Prop::OverflowY,
        Prop::Appearance,
        Prop::TableLayout,
        Prop::CaptionSide,
        Prop::BorderCollapse,
        Prop::BorderSpacing,
        Prop::ContainerType,
        Prop::ContainerName,
        Prop::CaretColor,
        Prop::TabSize,
        Prop::JustifyItems,
        Prop::JustifySelf,
        Prop::AlignContent,
        Prop::Direction,
        Prop::UnicodeBidi,
        Prop::Translate,
        Prop::Rotate,
        Prop::Scale,
        Prop::Perspective,
        Prop::PerspectiveOrigin,
        Prop::TransformBox,
        Prop::TransformStyle,
        Prop::BackfaceVisibility,
        Prop::AnimationPlayState,
        Prop::Clip,
        Prop::ContentVisibility,
        Prop::WritingMode,
        Prop::TextOrientation,
        Prop::TransitionDelay,
        Prop::TransitionDuration,
        Prop::AnimationDelay,
        Prop::AnimationDuration,
        Prop::Orphans,
        Prop::Widows,
        Prop::MaxLines,
        Prop::HyphenateLimitLines,
        Prop::ColumnSpan,
        Prop::BreakBefore,
        Prop::BreakAfter,
        Prop::BreakInside,
        Prop::ScrollSnapType,
        Prop::ScrollSnapAlign,
        Prop::ScrollSnapStop,
        Prop::ScrollPaddingTop,
        Prop::ScrollPaddingRight,
        Prop::ScrollPaddingBottom,
        Prop::ScrollPaddingLeft,
        Prop::ScrollMarginTop,
        Prop::ScrollMarginRight,
        Prop::ScrollMarginBottom,
        Prop::ScrollMarginLeft,
        Prop::BorderImageSource,
        Prop::BorderImageSlice,
        Prop::BorderImageWidth,
        Prop::BorderImageOutset,
        Prop::BorderImageRepeat,
        Prop::Fill,
        Prop::FillOpacity,
        Prop::FillRule,
        Prop::Stroke,
        Prop::StrokeWidth,
        Prop::StrokeOpacity,
        Prop::StrokeLinecap,
        Prop::StrokeLinejoin,
        Prop::StrokeMiterlimit,
        Prop::StrokeDasharray,
        Prop::StrokeDashoffset,
        Prop::StopColor,
        Prop::StopOpacity,
        Prop::ClipRule,
        Prop::TextAnchor,
        Prop::DominantBaseline,
        Prop::PaintOrder,
        Prop::VectorEffect,
        Prop::ShapeRendering,
        Prop::SvgX,
        Prop::SvgY,
        Prop::Cx,
        Prop::Cy,
        Prop::R,
        Prop::Rx,
        Prop::Ry,
        Prop::AnimationName,
        Prop::AnimationTimingFunction,
        Prop::AnimationIterationCount,
        Prop::AnimationDirection,
        Prop::AnimationFillMode,
        Prop::TransitionProperty,
        Prop::TransitionTimingFunction,
        Prop::TransitionBehavior,
        Prop::AnimationTimeline,
        Prop::AnimationRangeStart,
        Prop::AnimationRangeEnd,
        Prop::AnimationComposition,
        Prop::CounterSet,
        Prop::OverflowClipMargin,
        Prop::WebkitBoxOrient,
        Prop::MaskClip,
        Prop::MaskComposite,
    ];

    pub(crate) fn name(self) -> &'static [u8] {
        match self {
            Prop::Display => b"display",
            Prop::Color => b"color",
            Prop::BackgroundColor => b"background-color",
            Prop::FontSize => b"font-size",
            Prop::FontWeight => b"font-weight",
            Prop::FontStyle => b"font-style",
            Prop::FontStretch => b"font-stretch",
            Prop::FontKerning => b"font-kerning",
            Prop::FontVariantLigatures => b"font-variant-ligatures",
            Prop::FontFeatureSettings => b"font-feature-settings",
            Prop::FontVariationSettings => b"font-variation-settings",
            Prop::FontFamily => b"font-family",
            Prop::TextAlign => b"text-align",
            Prop::MarginTop => b"margin-top",
            Prop::MarginRight => b"margin-right",
            Prop::MarginBottom => b"margin-bottom",
            Prop::MarginLeft => b"margin-left",
            Prop::PaddingTop => b"padding-top",
            Prop::PaddingRight => b"padding-right",
            Prop::PaddingBottom => b"padding-bottom",
            Prop::PaddingLeft => b"padding-left",
            Prop::BorderTopWidth => b"border-top-width",
            Prop::BorderRightWidth => b"border-right-width",
            Prop::BorderBottomWidth => b"border-bottom-width",
            Prop::BorderLeftWidth => b"border-left-width",
            Prop::BorderTopColor => b"border-top-color",
            Prop::BorderRightColor => b"border-right-color",
            Prop::BorderBottomColor => b"border-bottom-color",
            Prop::BorderLeftColor => b"border-left-color",
            Prop::BorderTopStyle => b"border-top-style",
            Prop::BorderRightStyle => b"border-right-style",
            Prop::BorderBottomStyle => b"border-bottom-style",
            Prop::BorderLeftStyle => b"border-left-style",
            Prop::Width => b"width",
            Prop::Height => b"height",
            Prop::MaxWidth => b"max-width",
            Prop::MaxHeight => b"max-height",
            Prop::MinWidth => b"min-width",
            Prop::MinHeight => b"min-height",
            Prop::LineHeight => b"line-height",
            Prop::TextDecoration => b"text-decoration",
            Prop::Position => b"position",
            Prop::Top => b"top",
            Prop::Right => b"right",
            Prop::Bottom => b"bottom",
            Prop::Left => b"left",
            Prop::ZIndex => b"z-index",
            Prop::Opacity => b"opacity",
            Prop::Cursor => b"cursor",
            Prop::PointerEvents => b"pointer-events",
            Prop::LetterSpacing => b"letter-spacing",
            Prop::WordSpacing => b"word-spacing",
            Prop::WhiteSpace => b"white-space",
            Prop::BoxSizing => b"box-sizing",
            Prop::TextIndent => b"text-indent",
            Prop::TextTransform => b"text-transform",
            Prop::ListStyleType => b"list-style-type",
            Prop::VerticalAlign => b"vertical-align",
            Prop::Visibility => b"visibility",
            Prop::Overflow => b"overflow",
            Prop::FontVariant => b"font-variant",
            Prop::BorderRadius => b"border-radius",
            Prop::BorderTopLeftRadius => b"border-top-left-radius",
            Prop::BorderTopRightRadius => b"border-top-right-radius",
            Prop::BorderBottomRightRadius => b"border-bottom-right-radius",
            Prop::BorderBottomLeftRadius => b"border-bottom-left-radius",
            Prop::FlexDirection => b"flex-direction",
            Prop::FlexWrap => b"flex-wrap",
            Prop::JustifyContent => b"justify-content",
            Prop::AlignItems => b"align-items",
            Prop::AlignSelf => b"align-self",
            Prop::Gap => b"gap",
            Prop::RowGap => b"row-gap",
            Prop::ColumnGap => b"column-gap",
            Prop::FlexGrow => b"flex-grow",
            Prop::FlexShrink => b"flex-shrink",
            Prop::FlexBasis => b"flex-basis",
            Prop::Order => b"order",
            Prop::Float => b"float",
            Prop::Clear => b"clear",
            Prop::BoxShadow => b"box-shadow",
            Prop::OutlineWidth => b"outline-width",
            Prop::OutlineStyle => b"outline-style",
            Prop::OutlineColor => b"outline-color",
            Prop::OutlineOffset => b"outline-offset",
            Prop::BackgroundImage => b"background-image",
            Prop::BackgroundRepeat => b"background-repeat",
            Prop::BackgroundPositionX => b"background-position-x",
            Prop::BackgroundPositionY => b"background-position-y",
            Prop::BackgroundSize => b"background-size",
            Prop::BackgroundClip => b"background-clip",
            Prop::BackgroundOrigin => b"background-origin",
            Prop::BackgroundAttachment => b"background-attachment",
            Prop::ScrollbarWidth => b"scrollbar-width",
            Prop::ScrollbarColor => b"scrollbar-color",
            Prop::ImageRendering => b"image-rendering",
            Prop::Content => b"content",
            Prop::GridTemplateColumns => b"grid-template-columns",
            Prop::GridTemplateRows => b"grid-template-rows",
            Prop::GridTemplateAreas => b"grid-template-areas",
            Prop::GridColumn => b"grid-column",
            Prop::GridRow => b"grid-row",
            Prop::GridColumnStart => b"grid-column-start",
            Prop::GridColumnEnd => b"grid-column-end",
            Prop::GridRowStart => b"grid-row-start",
            Prop::GridRowEnd => b"grid-row-end",
            Prop::GridArea => b"grid-area",
            Prop::GridAutoRows => b"grid-auto-rows",
            Prop::GridAutoColumns => b"grid-auto-columns",
            Prop::GridAutoFlow => b"grid-auto-flow",
            Prop::Transform => b"transform",
            Prop::TransformOrigin => b"transform-origin",
            Prop::Transition => b"transition",
            Prop::Animation => b"animation",
            Prop::AspectRatio => b"aspect-ratio",
            Prop::TextShadow => b"text-shadow",
            Prop::OverflowWrap => b"overflow-wrap",
            Prop::WordBreak => b"word-break",
            Prop::Hyphens => b"hyphens",
            Prop::TextOverflow => b"text-overflow",
            Prop::TextDecorationColor => b"text-decoration-color",
            Prop::TextDecorationStyle => b"text-decoration-style",
            Prop::ListStylePosition => b"list-style-position",
            Prop::ListStyleImage => b"list-style-image",
            Prop::UserSelect => b"user-select",
            Prop::Quotes => b"quotes",
            Prop::ColumnCount => b"column-count",
            Prop::ColumnWidth => b"column-width",
            Prop::ColumnRuleWidth => b"column-rule-width",
            Prop::ColumnRuleStyle => b"column-rule-style",
            Prop::ColumnRuleColor => b"column-rule-color",
            Prop::Filter => b"filter",
            Prop::ClipPath => b"clip-path",
            Prop::MixBlendMode => b"mix-blend-mode",
            Prop::AccentColor => b"accent-color",
            Prop::CounterReset => b"counter-reset",
            Prop::CounterIncrement => b"counter-increment",
            Prop::LineClamp => b"-webkit-line-clamp",
            Prop::ObjectFit => b"object-fit",
            Prop::ObjectPositionX => b"object-position-x",
            Prop::ObjectPositionY => b"object-position-y",
            Prop::MaskImage => b"mask-image",
            Prop::OverflowX => b"overflow-x",
            Prop::OverflowY => b"overflow-y",
            Prop::Appearance => b"appearance",
            Prop::TableLayout => b"table-layout",
            Prop::CaptionSide => b"caption-side",
            Prop::BorderCollapse => b"border-collapse",
            Prop::BorderSpacing => b"border-spacing",
            Prop::ContainerType => b"container-type",
            Prop::ContainerName => b"container-name",
            Prop::CaretColor => b"caret-color",
            Prop::TabSize => b"tab-size",
            Prop::JustifyItems => b"justify-items",
            Prop::JustifySelf => b"justify-self",
            Prop::AlignContent => b"align-content",
            Prop::Direction => b"direction",
            Prop::UnicodeBidi => b"unicode-bidi",
            Prop::Translate => b"translate",
            Prop::Rotate => b"rotate",
            Prop::Scale => b"scale",
            Prop::Perspective => b"perspective",
            Prop::PerspectiveOrigin => b"perspective-origin",
            Prop::TransformBox => b"transform-box",
            Prop::TransformStyle => b"transform-style",
            Prop::BackfaceVisibility => b"backface-visibility",
            Prop::AnimationPlayState => b"animation-play-state",
            Prop::Clip => b"clip",
            Prop::ContentVisibility => b"content-visibility",
            Prop::WritingMode => b"writing-mode",
            Prop::TextOrientation => b"text-orientation",
            Prop::TransitionDelay => b"transition-delay",
            Prop::TransitionDuration => b"transition-duration",
            Prop::AnimationDelay => b"animation-delay",
            Prop::AnimationDuration => b"animation-duration",
            Prop::Orphans => b"orphans",
            Prop::Widows => b"widows",
            Prop::MaxLines => b"max-lines",
            Prop::HyphenateLimitLines => b"hyphenate-limit-lines",
            Prop::ColumnSpan => b"column-span",
            Prop::BreakBefore => b"break-before",
            Prop::BreakAfter => b"break-after",
            Prop::BreakInside => b"break-inside",
            Prop::ScrollSnapType => b"scroll-snap-type",
            Prop::ScrollSnapAlign => b"scroll-snap-align",
            Prop::ScrollSnapStop => b"scroll-snap-stop",
            Prop::ScrollPaddingTop => b"scroll-padding-top",
            Prop::ScrollPaddingRight => b"scroll-padding-right",
            Prop::ScrollPaddingBottom => b"scroll-padding-bottom",
            Prop::ScrollPaddingLeft => b"scroll-padding-left",
            Prop::ScrollMarginTop => b"scroll-margin-top",
            Prop::ScrollMarginRight => b"scroll-margin-right",
            Prop::ScrollMarginBottom => b"scroll-margin-bottom",
            Prop::ScrollMarginLeft => b"scroll-margin-left",
            Prop::BorderImageSource => b"border-image-source",
            Prop::BorderImageSlice => b"border-image-slice",
            Prop::BorderImageWidth => b"border-image-width",
            Prop::BorderImageOutset => b"border-image-outset",
            Prop::BorderImageRepeat => b"border-image-repeat",
            Prop::Fill => b"fill",
            Prop::FillOpacity => b"fill-opacity",
            Prop::FillRule => b"fill-rule",
            Prop::Stroke => b"stroke",
            Prop::StrokeWidth => b"stroke-width",
            Prop::StrokeOpacity => b"stroke-opacity",
            Prop::StrokeLinecap => b"stroke-linecap",
            Prop::StrokeLinejoin => b"stroke-linejoin",
            Prop::StrokeMiterlimit => b"stroke-miterlimit",
            Prop::StrokeDasharray => b"stroke-dasharray",
            Prop::StrokeDashoffset => b"stroke-dashoffset",
            Prop::StopColor => b"stop-color",
            Prop::StopOpacity => b"stop-opacity",
            Prop::ClipRule => b"clip-rule",
            Prop::TextAnchor => b"text-anchor",
            Prop::DominantBaseline => b"dominant-baseline",
            Prop::PaintOrder => b"paint-order",
            Prop::VectorEffect => b"vector-effect",
            Prop::ShapeRendering => b"shape-rendering",
            Prop::SvgX => b"x",
            Prop::SvgY => b"y",
            Prop::Cx => b"cx",
            Prop::Cy => b"cy",
            Prop::R => b"r",
            Prop::Rx => b"rx",
            Prop::Ry => b"ry",
            Prop::AnimationName => b"animation-name",
            Prop::AnimationTimingFunction => b"animation-timing-function",
            Prop::AnimationIterationCount => b"animation-iteration-count",
            Prop::AnimationDirection => b"animation-direction",
            Prop::AnimationFillMode => b"animation-fill-mode",
            Prop::TransitionProperty => b"transition-property",
            Prop::TransitionTimingFunction => b"transition-timing-function",
            Prop::TransitionBehavior => b"transition-behavior",
            Prop::AnimationTimeline => b"animation-timeline",
            Prop::AnimationRangeStart => b"animation-range-start",
            Prop::AnimationRangeEnd => b"animation-range-end",
            Prop::AnimationComposition => b"animation-composition",
            Prop::CounterSet => b"counter-set",
            Prop::OverflowClipMargin => b"overflow-clip-margin",
            Prop::WebkitBoxOrient => b"-webkit-box-orient",
            Prop::MaskClip => b"mask-clip",
            Prop::MaskComposite => b"mask-composite",
        }
    }
}
