//! Southstar — the CSS properties css.h enumerates, in its order so a property's id is its discriminant, with their names, the aliases and logical properties that resolve to them, whether they inherit and whether they only repaint.
//! Copyright 2026 Andreas Røsdal
//! SPDX-License-Identifier: LicenseRef-NSL-1.0 OR GPL-3.0-or-later

use core::ffi::CStr;
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum Prop {
    Display,
    Color,
    BackgroundColor,
    FontSize,
    FontWeight,
    FontStyle,
    FontStretch,
    FontKerning,
    FontVariantLigatures,
    FontFeatureSettings,
    FontVariationSettings,
    FontFamily,
    TextAlign,
    MarginTop,
    MarginRight,
    MarginBottom,
    MarginLeft,
    PaddingTop,
    PaddingRight,
    PaddingBottom,
    PaddingLeft,
    BorderTopWidth,
    BorderRightWidth,
    BorderBottomWidth,
    BorderLeftWidth,
    BorderTopColor,
    BorderRightColor,
    BorderBottomColor,
    BorderLeftColor,
    BorderTopStyle,
    BorderRightStyle,
    BorderBottomStyle,
    BorderLeftStyle,
    Width,
    Height,
    MaxWidth,
    MaxHeight,
    MinWidth,
    MinHeight,
    LineHeight,
    TextDecoration,
    Position,
    Top,
    Right,
    Bottom,
    Left,
    ZIndex,
    Opacity,
    Cursor,
    PointerEvents,
    LetterSpacing,
    WordSpacing,
    WhiteSpace,
    BoxSizing,
    TextIndent,
    TextTransform,
    ListStyleType,
    VerticalAlign,
    Visibility,
    Overflow,
    FontVariant,
    BorderRadius,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderBottomRightRadius,
    BorderBottomLeftRadius,
    FlexDirection,
    FlexWrap,
    JustifyContent,
    AlignItems,
    AlignSelf,
    Gap,
    RowGap,
    ColumnGap,
    FlexGrow,
    FlexShrink,
    FlexBasis,
    Order,
    Float,
    Clear,
    BoxShadow,
    OutlineWidth,
    OutlineStyle,
    OutlineColor,
    OutlineOffset,
    BackgroundImage,
    BackgroundRepeat,
    BackgroundPositionX,
    BackgroundPositionY,
    BackgroundSize,
    BackgroundClip,
    BackgroundOrigin,
    BackgroundAttachment,
    ScrollbarWidth,
    ScrollbarColor,
    ImageRendering,
    Content,
    GridTemplateColumns,
    GridTemplateRows,
    GridTemplateAreas,
    GridColumn,
    GridRow,
    GridColumnStart,
    GridColumnEnd,
    GridRowStart,
    GridRowEnd,
    GridArea,
    GridAutoRows,
    GridAutoColumns,
    GridAutoFlow,
    Transform,
    TransformOrigin,
    Transition,
    Animation,
    AspectRatio,
    TextShadow,
    OverflowWrap,
    WordBreak,
    Hyphens,
    TextOverflow,
    TextDecorationColor,
    TextDecorationStyle,
    ListStylePosition,
    ListStyleImage,
    UserSelect,
    Quotes,
    ColumnCount,
    ColumnWidth,
    ColumnRuleWidth,
    ColumnRuleStyle,
    ColumnRuleColor,
    Filter,
    ClipPath,
    MixBlendMode,
    AccentColor,
    CounterReset,
    CounterIncrement,
    LineClamp,
    ObjectFit,
    ObjectPositionX,
    ObjectPositionY,
    MaskImage,
    OverflowX,
    OverflowY,
    Appearance,
    TableLayout,
    CaptionSide,
    BorderCollapse,
    BorderSpacing,
    ContainerType,
    ContainerName,
    CaretColor,
    TabSize,
    JustifyItems,
    JustifySelf,
    AlignContent,
    Direction,
    UnicodeBidi,
    Translate,
    Rotate,
    Scale,
    Perspective,
    PerspectiveOrigin,
    TransformBox,
    TransformStyle,
    BackfaceVisibility,
    AnimationPlayState,
    Clip,
    ContentVisibility,
    WritingMode,
    TextOrientation,
    TransitionDelay,
    TransitionDuration,
    AnimationDelay,
    AnimationDuration,
    Orphans,
    Widows,
    MaxLines,
    HyphenateLimitLines,
    ColumnSpan,
    BreakBefore,
    BreakAfter,
    BreakInside,
    ScrollSnapType,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollPaddingTop,
    ScrollPaddingRight,
    ScrollPaddingBottom,
    ScrollPaddingLeft,
    ScrollMarginTop,
    ScrollMarginRight,
    ScrollMarginBottom,
    ScrollMarginLeft,
    BorderImageSource,
    BorderImageSlice,
    BorderImageWidth,
    BorderImageOutset,
    BorderImageRepeat,
    Fill,
    FillOpacity,
    FillRule,
    Stroke,
    StrokeWidth,
    StrokeOpacity,
    StrokeLinecap,
    StrokeLinejoin,
    StrokeMiterlimit,
    StrokeDasharray,
    StrokeDashoffset,
    StopColor,
    StopOpacity,
    ClipRule,
    TextAnchor,
    DominantBaseline,
    PaintOrder,
    VectorEffect,
    ShapeRendering,
    SvgX,
    SvgY,
    Cx,
    Cy,
    R,
    Rx,
    Ry,
    AnimationName,
    AnimationTimingFunction,
    AnimationIterationCount,
    AnimationDirection,
    AnimationFillMode,
    TransitionProperty,
    TransitionTimingFunction,
    TransitionBehavior,
    AnimationTimeline,
    AnimationRangeStart,
    AnimationRangeEnd,
    AnimationComposition,
    CounterSet,
    OverflowClipMargin,
    WebkitBoxOrient,
    MaskClip,
    MaskComposite,
}

impl Prop {
    pub(crate) const ALL: [Prop; 242] = [
        Prop::Display,
        Prop::Color,
        Prop::BackgroundColor,
        Prop::FontSize,
        Prop::FontWeight,
        Prop::FontStyle,
        Prop::FontStretch,
        Prop::FontKerning,
        Prop::FontVariantLigatures,
        Prop::FontFeatureSettings,
        Prop::FontVariationSettings,
        Prop::FontFamily,
        Prop::TextAlign,
        Prop::MarginTop,
        Prop::MarginRight,
        Prop::MarginBottom,
        Prop::MarginLeft,
        Prop::PaddingTop,
        Prop::PaddingRight,
        Prop::PaddingBottom,
        Prop::PaddingLeft,
        Prop::BorderTopWidth,
        Prop::BorderRightWidth,
        Prop::BorderBottomWidth,
        Prop::BorderLeftWidth,
        Prop::BorderTopColor,
        Prop::BorderRightColor,
        Prop::BorderBottomColor,
        Prop::BorderLeftColor,
        Prop::BorderTopStyle,
        Prop::BorderRightStyle,
        Prop::BorderBottomStyle,
        Prop::BorderLeftStyle,
        Prop::Width,
        Prop::Height,
        Prop::MaxWidth,
        Prop::MaxHeight,
        Prop::MinWidth,
        Prop::MinHeight,
        Prop::LineHeight,
        Prop::TextDecoration,
        Prop::Position,
        Prop::Top,
        Prop::Right,
        Prop::Bottom,
        Prop::Left,
        Prop::ZIndex,
        Prop::Opacity,
        Prop::Cursor,
        Prop::PointerEvents,
        Prop::LetterSpacing,
        Prop::WordSpacing,
        Prop::WhiteSpace,
        Prop::BoxSizing,
        Prop::TextIndent,
        Prop::TextTransform,
        Prop::ListStyleType,
        Prop::VerticalAlign,
        Prop::Visibility,
        Prop::Overflow,
        Prop::FontVariant,
        Prop::BorderRadius,
        Prop::BorderTopLeftRadius,
        Prop::BorderTopRightRadius,
        Prop::BorderBottomRightRadius,
        Prop::BorderBottomLeftRadius,
        Prop::FlexDirection,
        Prop::FlexWrap,
        Prop::JustifyContent,
        Prop::AlignItems,
        Prop::AlignSelf,
        Prop::Gap,
        Prop::RowGap,
        Prop::ColumnGap,
        Prop::FlexGrow,
        Prop::FlexShrink,
        Prop::FlexBasis,
        Prop::Order,
        Prop::Float,
        Prop::Clear,
        Prop::BoxShadow,
        Prop::OutlineWidth,
        Prop::OutlineStyle,
        Prop::OutlineColor,
        Prop::OutlineOffset,
        Prop::BackgroundImage,
        Prop::BackgroundRepeat,
        Prop::BackgroundPositionX,
        Prop::BackgroundPositionY,
        Prop::BackgroundSize,
        Prop::BackgroundClip,
        Prop::BackgroundOrigin,
        Prop::BackgroundAttachment,
        Prop::ScrollbarWidth,
        Prop::ScrollbarColor,
        Prop::ImageRendering,
        Prop::Content,
        Prop::GridTemplateColumns,
        Prop::GridTemplateRows,
        Prop::GridTemplateAreas,
        Prop::GridColumn,
        Prop::GridRow,
        Prop::GridColumnStart,
        Prop::GridColumnEnd,
        Prop::GridRowStart,
        Prop::GridRowEnd,
        Prop::GridArea,
        Prop::GridAutoRows,
        Prop::GridAutoColumns,
        Prop::GridAutoFlow,
        Prop::Transform,
        Prop::TransformOrigin,
        Prop::Transition,
        Prop::Animation,
        Prop::AspectRatio,
        Prop::TextShadow,
        Prop::OverflowWrap,
        Prop::WordBreak,
        Prop::Hyphens,
        Prop::TextOverflow,
        Prop::TextDecorationColor,
        Prop::TextDecorationStyle,
        Prop::ListStylePosition,
        Prop::ListStyleImage,
        Prop::UserSelect,
        Prop::Quotes,
        Prop::ColumnCount,
        Prop::ColumnWidth,
        Prop::ColumnRuleWidth,
        Prop::ColumnRuleStyle,
        Prop::ColumnRuleColor,
        Prop::Filter,
        Prop::ClipPath,
        Prop::MixBlendMode,
        Prop::AccentColor,
        Prop::CounterReset,
        Prop::CounterIncrement,
        Prop::LineClamp,
        Prop::ObjectFit,
        Prop::ObjectPositionX,
        Prop::ObjectPositionY,
        Prop::MaskImage,
        Prop::OverflowX,
        Prop::OverflowY,
        Prop::Appearance,
        Prop::TableLayout,
        Prop::CaptionSide,
        Prop::BorderCollapse,
        Prop::BorderSpacing,
        Prop::ContainerType,
        Prop::ContainerName,
        Prop::CaretColor,
        Prop::TabSize,
        Prop::JustifyItems,
        Prop::JustifySelf,
        Prop::AlignContent,
        Prop::Direction,
        Prop::UnicodeBidi,
        Prop::Translate,
        Prop::Rotate,
        Prop::Scale,
        Prop::Perspective,
        Prop::PerspectiveOrigin,
        Prop::TransformBox,
        Prop::TransformStyle,
        Prop::BackfaceVisibility,
        Prop::AnimationPlayState,
        Prop::Clip,
        Prop::ContentVisibility,
        Prop::WritingMode,
        Prop::TextOrientation,
        Prop::TransitionDelay,
        Prop::TransitionDuration,
        Prop::AnimationDelay,
        Prop::AnimationDuration,
        Prop::Orphans,
        Prop::Widows,
        Prop::MaxLines,
        Prop::HyphenateLimitLines,
        Prop::ColumnSpan,
        Prop::BreakBefore,
        Prop::BreakAfter,
        Prop::BreakInside,
        Prop::ScrollSnapType,
        Prop::ScrollSnapAlign,
        Prop::ScrollSnapStop,
        Prop::ScrollPaddingTop,
        Prop::ScrollPaddingRight,
        Prop::ScrollPaddingBottom,
        Prop::ScrollPaddingLeft,
        Prop::ScrollMarginTop,
        Prop::ScrollMarginRight,
        Prop::ScrollMarginBottom,
        Prop::ScrollMarginLeft,
        Prop::BorderImageSource,
        Prop::BorderImageSlice,
        Prop::BorderImageWidth,
        Prop::BorderImageOutset,
        Prop::BorderImageRepeat,
        Prop::Fill,
        Prop::FillOpacity,
        Prop::FillRule,
        Prop::Stroke,
        Prop::StrokeWidth,
        Prop::StrokeOpacity,
        Prop::StrokeLinecap,
        Prop::StrokeLinejoin,
        Prop::StrokeMiterlimit,
        Prop::StrokeDasharray,
        Prop::StrokeDashoffset,
        Prop::StopColor,
        Prop::StopOpacity,
        Prop::ClipRule,
        Prop::TextAnchor,
        Prop::DominantBaseline,
        Prop::PaintOrder,
        Prop::VectorEffect,
        Prop::ShapeRendering,
        Prop::SvgX,
        Prop::SvgY,
        Prop::Cx,
        Prop::Cy,
        Prop::R,
        Prop::Rx,
        Prop::Ry,
        Prop::AnimationName,
        Prop::AnimationTimingFunction,
        Prop::AnimationIterationCount,
        Prop::AnimationDirection,
        Prop::AnimationFillMode,
        Prop::TransitionProperty,
        Prop::TransitionTimingFunction,
        Prop::TransitionBehavior,
        Prop::AnimationTimeline,
        Prop::AnimationRangeStart,
        Prop::AnimationRangeEnd,
        Prop::AnimationComposition,
        Prop::CounterSet,
        Prop::OverflowClipMargin,
        Prop::WebkitBoxOrient,
        Prop::MaskClip,
        Prop::MaskComposite,
    ];

    pub(crate) fn name(self) -> &'static [u8] {
        self.c_name().to_bytes()
    }

    pub(crate) fn id(self) -> usize {
        self as usize
    }

    pub(crate) fn from_id(id: usize) -> Option<Prop> {
        Prop::ALL.get(id).copied()
    }

    pub(crate) fn from_name(name: &[u8]) -> Option<Prop> {
        names().get(name.to_ascii_lowercase().as_slice()).copied()
    }

    pub(crate) fn inherits(self) -> bool {
        matches!(
            self,
            Prop::Color
                | Prop::FontSize
                | Prop::FontWeight
                | Prop::FontStyle
                | Prop::FontStretch
                | Prop::FontKerning
                | Prop::FontVariantLigatures
                | Prop::FontFeatureSettings
                | Prop::FontVariationSettings
                | Prop::FontFamily
                | Prop::FontVariant
                | Prop::LineHeight
                | Prop::LetterSpacing
                | Prop::WordSpacing
                | Prop::WhiteSpace
                | Prop::Hyphens
                | Prop::Direction
                | Prop::WritingMode
                | Prop::TextOrientation
                | Prop::CaptionSide
                | Prop::BorderCollapse
                | Prop::BorderSpacing
                | Prop::TextAlign
                | Prop::TextIndent
                | Prop::TextTransform
                | Prop::ListStyleType
                | Prop::ListStylePosition
                | Prop::ListStyleImage
                | Prop::UserSelect
                | Prop::Quotes
                | Prop::Visibility
                | Prop::Cursor
                | Prop::PointerEvents
                | Prop::ScrollbarColor
                | Prop::ImageRendering
                | Prop::TabSize
                | Prop::WordBreak
                | Prop::OverflowWrap
                | Prop::CaretColor
                | Prop::AccentColor
                | Prop::Fill
                | Prop::FillOpacity
                | Prop::FillRule
                | Prop::Stroke
                | Prop::StrokeWidth
                | Prop::StrokeOpacity
                | Prop::StrokeLinecap
                | Prop::StrokeLinejoin
                | Prop::StrokeMiterlimit
                | Prop::StrokeDasharray
                | Prop::StrokeDashoffset
                | Prop::ClipRule
                | Prop::TextAnchor
                | Prop::PaintOrder
                | Prop::ShapeRendering
                | Prop::TextShadow
                | Prop::Orphans
                | Prop::Widows
                | Prop::DominantBaseline
        )
    }

    pub(crate) fn affects_layout(self) -> bool {
        !matches!(
            self,
            Prop::Opacity
                | Prop::Color
                | Prop::BackgroundColor
                | Prop::Transform
                | Prop::Visibility
                | Prop::BoxShadow
                | Prop::TextShadow
                | Prop::Filter
                | Prop::BorderTopColor
                | Prop::BorderRightColor
                | Prop::BorderBottomColor
                | Prop::BorderLeftColor
                | Prop::OutlineColor
        )
    }

    pub(crate) fn c_name(self) -> &'static CStr {
        match self {
            Prop::Display => c"display",
            Prop::Color => c"color",
            Prop::BackgroundColor => c"background-color",
            Prop::FontSize => c"font-size",
            Prop::FontWeight => c"font-weight",
            Prop::FontStyle => c"font-style",
            Prop::FontStretch => c"font-stretch",
            Prop::FontKerning => c"font-kerning",
            Prop::FontVariantLigatures => c"font-variant-ligatures",
            Prop::FontFeatureSettings => c"font-feature-settings",
            Prop::FontVariationSettings => c"font-variation-settings",
            Prop::FontFamily => c"font-family",
            Prop::TextAlign => c"text-align",
            Prop::MarginTop => c"margin-top",
            Prop::MarginRight => c"margin-right",
            Prop::MarginBottom => c"margin-bottom",
            Prop::MarginLeft => c"margin-left",
            Prop::PaddingTop => c"padding-top",
            Prop::PaddingRight => c"padding-right",
            Prop::PaddingBottom => c"padding-bottom",
            Prop::PaddingLeft => c"padding-left",
            Prop::BorderTopWidth => c"border-top-width",
            Prop::BorderRightWidth => c"border-right-width",
            Prop::BorderBottomWidth => c"border-bottom-width",
            Prop::BorderLeftWidth => c"border-left-width",
            Prop::BorderTopColor => c"border-top-color",
            Prop::BorderRightColor => c"border-right-color",
            Prop::BorderBottomColor => c"border-bottom-color",
            Prop::BorderLeftColor => c"border-left-color",
            Prop::BorderTopStyle => c"border-top-style",
            Prop::BorderRightStyle => c"border-right-style",
            Prop::BorderBottomStyle => c"border-bottom-style",
            Prop::BorderLeftStyle => c"border-left-style",
            Prop::Width => c"width",
            Prop::Height => c"height",
            Prop::MaxWidth => c"max-width",
            Prop::MaxHeight => c"max-height",
            Prop::MinWidth => c"min-width",
            Prop::MinHeight => c"min-height",
            Prop::LineHeight => c"line-height",
            Prop::TextDecoration => c"text-decoration",
            Prop::Position => c"position",
            Prop::Top => c"top",
            Prop::Right => c"right",
            Prop::Bottom => c"bottom",
            Prop::Left => c"left",
            Prop::ZIndex => c"z-index",
            Prop::Opacity => c"opacity",
            Prop::Cursor => c"cursor",
            Prop::PointerEvents => c"pointer-events",
            Prop::LetterSpacing => c"letter-spacing",
            Prop::WordSpacing => c"word-spacing",
            Prop::WhiteSpace => c"white-space",
            Prop::BoxSizing => c"box-sizing",
            Prop::TextIndent => c"text-indent",
            Prop::TextTransform => c"text-transform",
            Prop::ListStyleType => c"list-style-type",
            Prop::VerticalAlign => c"vertical-align",
            Prop::Visibility => c"visibility",
            Prop::Overflow => c"overflow",
            Prop::FontVariant => c"font-variant",
            Prop::BorderRadius => c"border-radius",
            Prop::BorderTopLeftRadius => c"border-top-left-radius",
            Prop::BorderTopRightRadius => c"border-top-right-radius",
            Prop::BorderBottomRightRadius => c"border-bottom-right-radius",
            Prop::BorderBottomLeftRadius => c"border-bottom-left-radius",
            Prop::FlexDirection => c"flex-direction",
            Prop::FlexWrap => c"flex-wrap",
            Prop::JustifyContent => c"justify-content",
            Prop::AlignItems => c"align-items",
            Prop::AlignSelf => c"align-self",
            Prop::Gap => c"gap",
            Prop::RowGap => c"row-gap",
            Prop::ColumnGap => c"column-gap",
            Prop::FlexGrow => c"flex-grow",
            Prop::FlexShrink => c"flex-shrink",
            Prop::FlexBasis => c"flex-basis",
            Prop::Order => c"order",
            Prop::Float => c"float",
            Prop::Clear => c"clear",
            Prop::BoxShadow => c"box-shadow",
            Prop::OutlineWidth => c"outline-width",
            Prop::OutlineStyle => c"outline-style",
            Prop::OutlineColor => c"outline-color",
            Prop::OutlineOffset => c"outline-offset",
            Prop::BackgroundImage => c"background-image",
            Prop::BackgroundRepeat => c"background-repeat",
            Prop::BackgroundPositionX => c"background-position-x",
            Prop::BackgroundPositionY => c"background-position-y",
            Prop::BackgroundSize => c"background-size",
            Prop::BackgroundClip => c"background-clip",
            Prop::BackgroundOrigin => c"background-origin",
            Prop::BackgroundAttachment => c"background-attachment",
            Prop::ScrollbarWidth => c"scrollbar-width",
            Prop::ScrollbarColor => c"scrollbar-color",
            Prop::ImageRendering => c"image-rendering",
            Prop::Content => c"content",
            Prop::GridTemplateColumns => c"grid-template-columns",
            Prop::GridTemplateRows => c"grid-template-rows",
            Prop::GridTemplateAreas => c"grid-template-areas",
            Prop::GridColumn => c"grid-column",
            Prop::GridRow => c"grid-row",
            Prop::GridColumnStart => c"grid-column-start",
            Prop::GridColumnEnd => c"grid-column-end",
            Prop::GridRowStart => c"grid-row-start",
            Prop::GridRowEnd => c"grid-row-end",
            Prop::GridArea => c"grid-area",
            Prop::GridAutoRows => c"grid-auto-rows",
            Prop::GridAutoColumns => c"grid-auto-columns",
            Prop::GridAutoFlow => c"grid-auto-flow",
            Prop::Transform => c"transform",
            Prop::TransformOrigin => c"transform-origin",
            Prop::Transition => c"transition",
            Prop::Animation => c"animation",
            Prop::AspectRatio => c"aspect-ratio",
            Prop::TextShadow => c"text-shadow",
            Prop::OverflowWrap => c"overflow-wrap",
            Prop::WordBreak => c"word-break",
            Prop::Hyphens => c"hyphens",
            Prop::TextOverflow => c"text-overflow",
            Prop::TextDecorationColor => c"text-decoration-color",
            Prop::TextDecorationStyle => c"text-decoration-style",
            Prop::ListStylePosition => c"list-style-position",
            Prop::ListStyleImage => c"list-style-image",
            Prop::UserSelect => c"user-select",
            Prop::Quotes => c"quotes",
            Prop::ColumnCount => c"column-count",
            Prop::ColumnWidth => c"column-width",
            Prop::ColumnRuleWidth => c"column-rule-width",
            Prop::ColumnRuleStyle => c"column-rule-style",
            Prop::ColumnRuleColor => c"column-rule-color",
            Prop::Filter => c"filter",
            Prop::ClipPath => c"clip-path",
            Prop::MixBlendMode => c"mix-blend-mode",
            Prop::AccentColor => c"accent-color",
            Prop::CounterReset => c"counter-reset",
            Prop::CounterIncrement => c"counter-increment",
            Prop::LineClamp => c"-webkit-line-clamp",
            Prop::ObjectFit => c"object-fit",
            Prop::ObjectPositionX => c"object-position-x",
            Prop::ObjectPositionY => c"object-position-y",
            Prop::MaskImage => c"mask-image",
            Prop::OverflowX => c"overflow-x",
            Prop::OverflowY => c"overflow-y",
            Prop::Appearance => c"appearance",
            Prop::TableLayout => c"table-layout",
            Prop::CaptionSide => c"caption-side",
            Prop::BorderCollapse => c"border-collapse",
            Prop::BorderSpacing => c"border-spacing",
            Prop::ContainerType => c"container-type",
            Prop::ContainerName => c"container-name",
            Prop::CaretColor => c"caret-color",
            Prop::TabSize => c"tab-size",
            Prop::JustifyItems => c"justify-items",
            Prop::JustifySelf => c"justify-self",
            Prop::AlignContent => c"align-content",
            Prop::Direction => c"direction",
            Prop::UnicodeBidi => c"unicode-bidi",
            Prop::Translate => c"translate",
            Prop::Rotate => c"rotate",
            Prop::Scale => c"scale",
            Prop::Perspective => c"perspective",
            Prop::PerspectiveOrigin => c"perspective-origin",
            Prop::TransformBox => c"transform-box",
            Prop::TransformStyle => c"transform-style",
            Prop::BackfaceVisibility => c"backface-visibility",
            Prop::AnimationPlayState => c"animation-play-state",
            Prop::Clip => c"clip",
            Prop::ContentVisibility => c"content-visibility",
            Prop::WritingMode => c"writing-mode",
            Prop::TextOrientation => c"text-orientation",
            Prop::TransitionDelay => c"transition-delay",
            Prop::TransitionDuration => c"transition-duration",
            Prop::AnimationDelay => c"animation-delay",
            Prop::AnimationDuration => c"animation-duration",
            Prop::Orphans => c"orphans",
            Prop::Widows => c"widows",
            Prop::MaxLines => c"max-lines",
            Prop::HyphenateLimitLines => c"hyphenate-limit-lines",
            Prop::ColumnSpan => c"column-span",
            Prop::BreakBefore => c"break-before",
            Prop::BreakAfter => c"break-after",
            Prop::BreakInside => c"break-inside",
            Prop::ScrollSnapType => c"scroll-snap-type",
            Prop::ScrollSnapAlign => c"scroll-snap-align",
            Prop::ScrollSnapStop => c"scroll-snap-stop",
            Prop::ScrollPaddingTop => c"scroll-padding-top",
            Prop::ScrollPaddingRight => c"scroll-padding-right",
            Prop::ScrollPaddingBottom => c"scroll-padding-bottom",
            Prop::ScrollPaddingLeft => c"scroll-padding-left",
            Prop::ScrollMarginTop => c"scroll-margin-top",
            Prop::ScrollMarginRight => c"scroll-margin-right",
            Prop::ScrollMarginBottom => c"scroll-margin-bottom",
            Prop::ScrollMarginLeft => c"scroll-margin-left",
            Prop::BorderImageSource => c"border-image-source",
            Prop::BorderImageSlice => c"border-image-slice",
            Prop::BorderImageWidth => c"border-image-width",
            Prop::BorderImageOutset => c"border-image-outset",
            Prop::BorderImageRepeat => c"border-image-repeat",
            Prop::Fill => c"fill",
            Prop::FillOpacity => c"fill-opacity",
            Prop::FillRule => c"fill-rule",
            Prop::Stroke => c"stroke",
            Prop::StrokeWidth => c"stroke-width",
            Prop::StrokeOpacity => c"stroke-opacity",
            Prop::StrokeLinecap => c"stroke-linecap",
            Prop::StrokeLinejoin => c"stroke-linejoin",
            Prop::StrokeMiterlimit => c"stroke-miterlimit",
            Prop::StrokeDasharray => c"stroke-dasharray",
            Prop::StrokeDashoffset => c"stroke-dashoffset",
            Prop::StopColor => c"stop-color",
            Prop::StopOpacity => c"stop-opacity",
            Prop::ClipRule => c"clip-rule",
            Prop::TextAnchor => c"text-anchor",
            Prop::DominantBaseline => c"dominant-baseline",
            Prop::PaintOrder => c"paint-order",
            Prop::VectorEffect => c"vector-effect",
            Prop::ShapeRendering => c"shape-rendering",
            Prop::SvgX => c"x",
            Prop::SvgY => c"y",
            Prop::Cx => c"cx",
            Prop::Cy => c"cy",
            Prop::R => c"r",
            Prop::Rx => c"rx",
            Prop::Ry => c"ry",
            Prop::AnimationName => c"animation-name",
            Prop::AnimationTimingFunction => c"animation-timing-function",
            Prop::AnimationIterationCount => c"animation-iteration-count",
            Prop::AnimationDirection => c"animation-direction",
            Prop::AnimationFillMode => c"animation-fill-mode",
            Prop::TransitionProperty => c"transition-property",
            Prop::TransitionTimingFunction => c"transition-timing-function",
            Prop::TransitionBehavior => c"transition-behavior",
            Prop::AnimationTimeline => c"animation-timeline",
            Prop::AnimationRangeStart => c"animation-range-start",
            Prop::AnimationRangeEnd => c"animation-range-end",
            Prop::AnimationComposition => c"animation-composition",
            Prop::CounterSet => c"counter-set",
            Prop::OverflowClipMargin => c"overflow-clip-margin",
            Prop::WebkitBoxOrient => c"-webkit-box-orient",
            Prop::MaskClip => c"mask-clip",
            Prop::MaskComposite => c"mask-composite",
        }
    }
}

const ALIASES: [(&[u8], Prop); 16] = [
    (b"word-wrap", Prop::OverflowWrap),
    (b"text-decoration-line", Prop::TextDecoration),
    (b"line-clamp", Prop::LineClamp),
    (b"text-wrap", Prop::WhiteSpace),
    (b"text-wrap-mode", Prop::WhiteSpace),
    (b"-webkit-mask-image", Prop::MaskImage),
    (b"-webkit-mask-clip", Prop::MaskClip),
    (b"-webkit-mask-composite", Prop::MaskComposite),
    (b"-webkit-background-clip", Prop::BackgroundClip),
    (b"-webkit-border-radius", Prop::BorderRadius),
    (b"-webkit-border-top-left-radius", Prop::BorderTopLeftRadius),
    (
        b"-webkit-border-top-right-radius",
        Prop::BorderTopRightRadius,
    ),
    (
        b"-webkit-border-bottom-right-radius",
        Prop::BorderBottomRightRadius,
    ),
    (
        b"-webkit-border-bottom-left-radius",
        Prop::BorderBottomLeftRadius,
    ),
    (b"-webkit-appearance", Prop::Appearance),
    (b"-moz-appearance", Prop::Appearance),
];

const LOGICAL: [(&[u8], &[u8]); 34] = [
    (b"margin-block-start", b"margin-top"),
    (b"margin-block-end", b"margin-bottom"),
    (b"margin-inline-start", b"margin-left"),
    (b"margin-inline-end", b"margin-right"),
    (b"padding-block-start", b"padding-top"),
    (b"padding-block-end", b"padding-bottom"),
    (b"padding-inline-start", b"padding-left"),
    (b"padding-inline-end", b"padding-right"),
    (b"border-block-start-width", b"border-top-width"),
    (b"border-block-end-width", b"border-bottom-width"),
    (b"border-inline-start-width", b"border-left-width"),
    (b"border-inline-end-width", b"border-right-width"),
    (b"border-block-start-style", b"border-top-style"),
    (b"border-block-end-style", b"border-bottom-style"),
    (b"border-inline-start-style", b"border-left-style"),
    (b"border-inline-end-style", b"border-right-style"),
    (b"border-block-start-color", b"border-top-color"),
    (b"border-block-end-color", b"border-bottom-color"),
    (b"border-inline-start-color", b"border-left-color"),
    (b"border-inline-end-color", b"border-right-color"),
    (b"border-start-start-radius", b"border-top-left-radius"),
    (b"border-start-end-radius", b"border-top-right-radius"),
    (b"border-end-start-radius", b"border-bottom-left-radius"),
    (b"border-end-end-radius", b"border-bottom-right-radius"),
    (b"inset-block-start", b"top"),
    (b"inset-block-end", b"bottom"),
    (b"inset-inline-start", b"left"),
    (b"inset-inline-end", b"right"),
    (b"block-size", b"height"),
    (b"inline-size", b"width"),
    (b"min-block-size", b"min-height"),
    (b"min-inline-size", b"min-width"),
    (b"max-block-size", b"max-height"),
    (b"max-inline-size", b"max-width"),
];

fn names() -> &'static HashMap<Vec<u8>, Prop> {
    static NAMES: OnceLock<HashMap<Vec<u8>, Prop>> = OnceLock::new();
    NAMES.get_or_init(|| {
        let mut names = HashMap::new();
        for prop in Prop::ALL {
            names.entry(prop.name().to_vec()).or_insert(prop);
        }
        for (alias, prop) in ALIASES {
            names.entry(alias.to_vec()).or_insert(prop);
        }
        for (logical, physical) in LOGICAL {
            if let Some(prop) = Prop::ALL.iter().find(|p| p.name() == physical) {
                names.entry(logical.to_vec()).or_insert(*prop);
            }
        }
        names
    })
}
