#!/usr/bin/env python3
"""Regenerate src/ns_pango_names.h from the engine's own usage.

The engine spells text layout in the ns-pango fork's renamed API. Builds that
link the system Pango instead (-Dns-pango=disabled) include the generated
header to map each name back to its stock spelling.

Names under ns_pango_cache_ are the fork's own additions with no stock
equivalent; every use of them must sit behind #ifdef NS_USE_NS_PANGO, so they
are deliberately left unmapped.
"""
import glob
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, 'src', 'ns_pango_names.h')
SKIP_FILES = {'ns_pango.h', 'ns_pango_names.h'}
FORK_ONLY = ('ns_pango_cache_',)

NAME = re.compile(r'\b(ns_pango_[a-z0-9_]+'
                  r'|NsPango[A-Za-z0-9_]+'
                  r'|NS_TYPE_PANGO_[A-Z0-9_]+'
                  r'|NS_PANGO_[A-Z0-9_]+)\b')
NOT_PANGO = {'NS_USE_NS_PANGO', 'NS_PANGO_H', 'NS_PANGO_NAMES_H'}


def stock(name):
    for prefix, replacement in (('ns_pango_', 'pango_'),
                                ('NsPango', 'Pango'),
                                ('NS_TYPE_PANGO_', 'PANGO_TYPE_'),
                                ('NS_PANGO_', 'PANGO_')):
        if name.startswith(prefix):
            return replacement + name[len(prefix):]
    raise SystemExit('cannot map %s' % name)


def main():
    names = set()
    for path in sorted(glob.glob(os.path.join(ROOT, 'src', '*.c')) +
                       glob.glob(os.path.join(ROOT, 'src', '*.h'))):
        if os.path.basename(path) in SKIP_FILES:
            continue
        with io.open(path, encoding='utf-8', errors='surrogateescape') as f:
            names |= set(NAME.findall(f.read()))

    names -= NOT_PANGO
    names = {n for n in names if not n.startswith(FORK_ONLY)}
    rows = sorted(names, key=lambda n: (n.lower(), n))
    width = max(len(n) for n in rows) + 1

    body = [
        '/* Nordstjernen — stock-Pango names for the fork\'s renamed API.',
        ' * Copyright 2026 Andreas Røsdal',
        ' * SPDX-License-Identifier: LicenseRef-NSL-1.0 OR GPL-3.0-or-later',
        ' */',
        '',
        '#ifndef NS_PANGO_NAMES_H',
        '#define NS_PANGO_NAMES_H',
        '',
        '/* Generated by scripts/gen-ns-pango-names.py — do not edit. */',
        '',
    ]
    body += ['#define %-*s %s' % (width, n, stock(n)) for n in rows]
    body += ['', '#endif /* NS_PANGO_NAMES_H */', '']

    with io.open(HEADER, 'w', encoding='utf-8', newline='') as f:
        f.write('\n'.join(body))
    print('%s: %d mappings' % (os.path.relpath(HEADER, ROOT), len(rows)))


if __name__ == '__main__':
    sys.exit(main())
